In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
myArray = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
indexes = [3, 5, 7]
modifiedArray = np.delete(myArray, indexes)
print(modifiedArray)

[ 1  2  3  5  7  9 10]


In [5]:
np.s_[::2]

slice(None, None, 2)

In [29]:
def filtrar(data):
    for j in range(data.shape[1]):
        for i in range(0,data.shape[0]-4,2):
            data = np.delete(data,i,j)

In [46]:
data = np.genfromtxt("data.dat", delimiter = ",")
data = data[0:5,0:4]

In [47]:
data.shape

(5, 4)

In [48]:
data

array([[0.00000e+00, 2.00000e+00, 4.44698e-04, 1.00000e+00],
       [0.00000e+00, 2.00000e+00, 8.89396e-04, 9.99999e-01],
       [1.00000e-03, 2.00000e+00, 1.33409e-03, 9.99998e-01],
       [2.00000e-03, 2.00000e+00, 1.77879e-03, 9.99997e-01],
       [3.00000e-03, 2.00000e+00, 2.22349e-03, 9.99996e-01]])

In [49]:
data = np.delete(data,0,0)
print(data)

[[0.00000e+00 2.00000e+00 8.89396e-04 9.99999e-01]
 [1.00000e-03 2.00000e+00 1.33409e-03 9.99998e-01]
 [2.00000e-03 2.00000e+00 1.77879e-03 9.99997e-01]
 [3.00000e-03 2.00000e+00 2.22349e-03 9.99996e-01]]


In [50]:
data.shape

(4, 4)